---

- name: install base packages
  become: true
  pacman:
    name:
        - yay
        - gvim
        - git
        - wget
        - curl
        - tree
        - python-pip
        - cmake
        - clang
        - gcc
        - stow
        - xorg-setxkbmap
        - xcape
        - xclip
        - xsel
        - sshpass
    state: present

- name: Install some useful command line utilities
  become: true
  pacman:
    name:
        - rofi
        - playerctl
        - glances
        - htop
        - nethogs
        - surfraw
        - ranger
        - scrot
        - imagemagick
        - fasd
        - ripgrep
        - fd
        - bat

- name: Install some desktop programs
  become: true
  pacman:
      name:
          - thunderbird
          - firefox
          - chromium
          - telegram-desktop
          - emacs
          - code
          - nextcloud-client
          - zathura
          - zathura-djvu
          - zathura-pdf-poppler
          - mpv
          - rofi
          - redshift
          - octave
          - libreoffice-still
          - calibre
          
      state: present

- name: Install some good looking app and icons themes
  become: true
  pacman:
      name: 
        - numix-gtk-theme
        - papirus-icon-theme
        - paper-icon-theme-git

- name: Install some fonts
  become: true
  pacman:
      name:
          - otf-fira-code
          - otf-fira-mono
          - otf-fira-sans
          - ttf-fira-code
          - ttf-fira-mono
          - ttf-fira-sans
       

- name: Install apps from the AUR
  become: false
  aur:
    skip_installed: true
    name:
      - dropbox
      - spotify
      - bitwarden-bin
      - acestream-engine
      - acestream-launcher
      - libselinux


- import_tasks: pacman.yml
  tags:
    - pkg

- import_tasks: pip.yml

# - import_tasks: anaconda.yml
