---

- name: install base packages
  become: true
  pacman:
    name:
        - vim
        - git
        - wget
        - curl
        - tree
        - python-pip
        - cmake
        - clang
        - gcc
    state: present


- name: install desktop programs
  become: true
  pacman:
      name:
          - thunderbird
          - firefox
          - telegram-desktop
          - emacs
          - code
