---

- name: install base packages
  become: true
  pacman:
    name:
        - vim
        - git
        - wget
        - curl
        - tree
        - python-pip
        - cmake
        - clang
        - gcc
    state: present


- name: install desktop programs
  become: true
  pacman:
      name:
          - thunderbird
          - firefox
          - telegram-desktop
          - emacs
          - code

- name: install config files
  git:
      repo: ssh://git@github.com/geeanlooca/dotfiles.fit
      dest: /home/gianluca/dotfiles
      update: yes
      accept_hostkey: yes

