---

- name: install base packages
  become: true
  pacman:
    name:
        - vim
        - git
        - wget
        - curl
        - tree
        - python-pip
        - cmake
        - clang
        - gcc
    state: present


- name: install desktop programs
  become: true
  pacman:
      name:
          - thunderbird
          - firefox
          - telegram-desktop
          - emacs
          - code
      state: present

- name: install config files
  git:
      repo: https://github.com/geeanlooca/dotfiles
      dest: /home/gianluca/dotfiles
      update: yes

- name: install themes
  become: true
  pacman:
      name: 
        - numix-gtk-theme
        - papirus-icon-theme
        - adapta-kde
